#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : haveged
Version  : 1.9.8
Release  : 2
URL      : https://github.com/jirka-h/haveged/archive/v1.9.8/haveged-1.9.8.tar.gz
Source0  : https://github.com/jirka-h/haveged/archive/v1.9.8/haveged-1.9.8.tar.gz
Source1  : haveged.service
Summary  : Entropy harvesting daemon using CPU timings
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+
Requires: haveged-bin = %{version}-%{release}
Requires: haveged-lib = %{version}-%{release}
Requires: haveged-license = %{version}-%{release}
Requires: haveged-man = %{version}-%{release}
Requires: haveged-services = %{version}-%{release}
Patch1: haveged-no-syslog.patch

%description
A Linux entropy source using the HAVEGE algorithm

Haveged is a user space entropy daemon which is not dependent upon the
standard mechanisms for harvesting randomness for the system entropy
pool. This is important in systems with high entropy needs or limited
user interaction (e.g. headless servers).

Haveged uses HAVEGE (HArdware Volatile Entropy Gathering and
Expansion) to maintain a 1M pool of random bytes used to fill
/dev/random whenever the supply of random bits in /dev/random falls
below the low water mark of the device. The principle inputs to
haveged are the sizes of the processor instruction and data caches
used to setup the HAVEGE collector. The haveged default is a 4kb data
cache and a 16kb instruction cache. On machines with a cpuid
instruction, haveged will attempt to select appropriate values from
internal tables.

%package bin
Summary: bin components for the haveged package.
Group: Binaries
Requires: haveged-license = %{version}-%{release}
Requires: haveged-services = %{version}-%{release}

%description bin
bin components for the haveged package.


%package dev
Summary: dev components for the haveged package.
Group: Development
Requires: haveged-lib = %{version}-%{release}
Requires: haveged-bin = %{version}-%{release}
Provides: haveged-devel = %{version}-%{release}
Requires: haveged = %{version}-%{release}
Requires: haveged = %{version}-%{release}

%description dev
dev components for the haveged package.


%package lib
Summary: lib components for the haveged package.
Group: Libraries
Requires: haveged-license = %{version}-%{release}

%description lib
lib components for the haveged package.


%package license
Summary: license components for the haveged package.
Group: Default

%description license
license components for the haveged package.


%package man
Summary: man components for the haveged package.
Group: Default

%description man
man components for the haveged package.


%package services
Summary: services components for the haveged package.
Group: Systemd services

%description services
services components for the haveged package.


%prep
%setup -q -n haveged-1.9.8
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570112827
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --enable-daemon \
--enable-clock_gettime
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1570112827
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/haveged
cp COPYING %{buildroot}/usr/share/package-licenses/haveged/COPYING
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/haveged.service

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/haveged

%files dev
%defattr(-,root,root,-)
/usr/include/haveged/havege.h
/usr/lib64/libhavege.so
/usr/share/man/man3/libhavege.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhavege.so.1
/usr/lib64/libhavege.so.1.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/haveged/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/haveged.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/haveged.service
